import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairCase from "@/components/StairCase";

const jetBrains_Mono = JetBrains_Mono({ subsets: ["latin"] ,weight:["100","200","300","400","500","600","700","800"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetBrains_Mono.variable}>
        <Header/>
        <StairCase/>
        <PageTransition>
        {children}
        </PageTransition>
        </body>
    </html>
  );
}
